import { Feather } from '@expo/vector-icons';
import React, { useState } from 'react';
import { FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { EntryModal } from '@/components/EntryModal';
import { useColors } from '@/hooks/useColors';
import { useKhata } from '@/context/KhataContext';
const money = (n: number) => `৳ ${n.toLocaleString('bn-BD')}`;
export default function Home() {
  const c = useColors(); const insets = useSafeAreaInsets(); const { entries, totalReceivable, totalPayable, totalExpenses } = useKhata(); const [modal, setModal] = useState(false);
  return <View style={[s.root, { backgroundColor: c.background, paddingTop: insets.top }]}><FlatList data={entries.slice(0, 6)} keyExtractor={e => e.id} contentContainerStyle={s.content} ListHeaderComponent={<><View style={s.header}><View><Text style={[s.eyebrow, { color: c.primary }]}>আজকের হিসাব</Text><Text style={[s.heading, { color: c.foreground }]}>আসসালামু আলাইকুম</Text><Text style={{ color: c.mutedForeground }}>আপনার ব্যবসার এক নজরের চিত্র</Text></View><View style={[s.logo, { backgroundColor: c.primary }]}><Feather name="book-open" size={22} color={c.primaryForeground} /></View></View><View style={[s.hero, { backgroundColor: c.secondary }]}><Text style={{ color: c.secondaryForeground, fontWeight: '700' }}>মোট বাকি পাওনা</Text><Text style={[s.heroMoney, { color: c.secondaryForeground }]}>{money(totalReceivable - totalPayable)}</Text><Text style={{ color: c.mutedForeground }}>সর্বশেষ আপডেট: আজ</Text></View><View style={s.stats}><Stat label="পাওনা" value={totalReceivable} color={c.primary} /><Stat label="দেনা" value={totalPayable} color="#477A5A" /><Stat label="খরচ" value={totalExpenses} color="#B35B56" /></View><Pressable onPress={() => setModal(true)} style={[s.add, { backgroundColor: c.primary }]}><Feather name="plus" size={20} color={c.primaryForeground} /><Text style={{ color: c.primaryForeground, fontWeight: '800', fontSize: 16 }}>নতুন হিসাব যোগ করুন</Text></Pressable><Text style={[s.section, { color: c.foreground }]}>সাম্প্রতিক লেনদেন</Text></>} ListEmptyComponent={<View style={s.empty}><Feather name="inbox" size={30} color={c.mutedForeground} /><Text style={{ color: c.mutedForeground }}>এখনো কোনো লেনদেন নেই</Text></View>} renderItem={({ item }) => <View style={[s.row, { backgroundColor: c.card, borderColor: c.border }]}><View style={[s.dot, { backgroundColor: item.type === 'receive' ? c.primary : item.type === 'give' ? '#477A5A' : '#B35B56' }]} /><View style={{ flex: 1 }}><Text style={[s.rowTitle, { color: c.foreground }]}>{item.personName ?? 'ব্যবসার খরচ'}</Text><Text style={{ color: c.mutedForeground }}>{item.note}</Text></View><Text style={{ color: item.type === 'receive' ? c.primary : '#B35B56', fontWeight: '800' }}>{item.type === 'receive' ? '+' : '-'}{money(item.amount)}</Text></View>} /><EntryModal visible={modal} onClose={() => setModal(false)} /></View>;
}
function Stat({ label, value, color }: { label: string; value: number; color: string }) { return <View style={s.stat}><Text style={{ color: '#718078', fontSize: 12 }}>{label}</Text><Text style={{ color, fontWeight: '800', fontSize: 16 }}>{money(value)}</Text></View>; }
const s = StyleSheet.create({ root: { flex: 1 }, content: { padding: 20, paddingBottom: 100, gap: 14 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 18 }, eyebrow: { fontSize: 13, fontWeight: '800', letterSpacing: 1 }, heading: { fontSize: 27, fontWeight: '800', marginTop: 4 }, logo: { width: 46, height: 46, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, hero: { borderRadius: 22, padding: 20, gap: 5 }, heroMoney: { fontSize: 33, fontWeight: '800' }, stats: { flexDirection: 'row', gap: 10 }, stat: { flex: 1, backgroundColor: '#FFFDF9', borderRadius: 15, padding: 13, gap: 5 }, add: { borderRadius: 16, padding: 15, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8 }, section: { fontSize: 19, fontWeight: '800', marginTop: 5 }, row: { borderWidth: 1, borderRadius: 16, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 11 }, dot: { width: 10, height: 10, borderRadius: 5 }, rowTitle: { fontSize: 15, fontWeight: '700' }, empty: { alignItems: 'center', gap: 10, paddingVertical: 35 } });